development:
  address: ENV["SMTP_ADDRESS"],
  port: ENV["SMTP_PORT"],
  authentication: plain,
  user_name: ENV["SMTP_USER_NAME"],
  password: ENV["SMTP_PASSWORD"],
  domain: ENV["SMTP_DOMAIN"],
  enable_starttls_auto: true
production:
  address: ENV["SMTP_ADDRESS"],
  port: ENV["SMTP_PORT"],
  authentication: plain,
  user_name: ENV["SMTP_USER_NAME"],
  password: ENV["SMTP_PASSWORD"],
  domain: ENV["SMTP_DOMAIN"],
  enable_starttls_auto: true
test:
  address: ENV["SMTP_ADDRESS"],
  port: ENV["SMTP_PORT"],
  authentication: plain,
  user_name: ENV["SMTP_USER_NAME"],
  password: ENV["SMTP_PASSWORD"],
  domain: ENV["SMTP_DOMAIN"],
  enable_starttls_auto: true
